import * as snarkjs from 'snarkjs';

/**
 * Generates a Zero-Knowledge Proof that the user is a student.
 * Uses a Circom circuit that checks if the Student ID hash exists in a known set.
 * 
 * @param {Object} input - Private and public inputs (e.g. { studentId: '123', univHash: '...' })
 * @returns {Promise<Object>} - The generated proof and public signals
 */
export async function generateStudentProof(input) {
    try {
        console.log('🛡️ Generating Zero-Knowledge Proof...');

        // In a real implementation, these files would be hosted on a CDN or 
        // public directory. They are generated by the Circom compiler.
        const wasmPath = '/zk/student_verifier.wasm';
        const zkeyPath = '/zk/student_verifier_final.zkey';

        /**
         * snarkjs.groth16.fullProve:
         * 1. Calculates the witness (using WASM)
         * 2. Generates the proof (using ZKEY)
         */
        const { proof, publicSignals } = await snarkjs.groth16.fullProve(
            input,
            wasmPath,
            zkeyPath
        );

        console.log('✅ Proof generated successfully');

        return {
            proof,
            publicSignals,
            universityHash: publicSignals[0] // Assuming first public signal is the univ commitment
        };
    } catch (error) {
        console.error('❌ ZKP Generation Failed:', error);
        throw new Error('Failed to generate security proof. Ensure your ID is valid.');
    }
}

/**
 * Utility to format proof for Solidity/Contract calls if needed
 */
export function formatProofForContract(proof) {
    return {
        a: [proof.pi_a[0], proof.pi_a[1]],
        b: [
            [proof.pi_b[0][1], proof.pi_b[0][0]],
            [proof.pi_b[1][1], proof.pi_b[1][0]],
        ],
        c: [proof.pi_c[0], proof.pi_c[1]],
    };
}
